### ISSUE TITLE
"peewee.OperationalError: no such column: t1.email" on login

### ISSUE THREAD

**Issue by rkkoszewski** [EstudioNexos/LXC-Web-Panel#11]
Is something missing in the database file from the repo? I get an error peewee.OperationalError: no such column: t1.email whenever I try to login. 

* Auth type: database
 * Missing session_secret file, your session will not survive server reboot. Run with --generate-session-secret to generate permanent file.
 * Serving Flask app "lwp" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
10.9.200.6 - - [04/Jan/2019 09:26:47] "GET / HTTP/1.1" 200 -
[2019-01-04 09:26:53,488] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/peewee-3.8.0-py3.5-linux-armv7l.egg/peewee.py", line 2711, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such column: t1.email

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/Flask-1.0.2-py3.5.egg/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/lwp-0.11b1-py3.5.egg/lwp/views/auth.py", line 38, in login
    user = AUTH_INSTANCE.authenticate(request_username, request_passwd)
  File "/usr/local/lib/python3.5/dist-packages/lwp-0.11b1-py3.5.egg/lwp/authenticators/database.py", line 10, in authenticate
    return results[0] if len(results) > 0 else None
  File "/usr/local/lib/python3.5/dist-packages/peewee-3.8.0-py3.5-linux-armv7l.egg/peewee.py", line 1723, in __len__
    self._ensure_execution()
  File "/usr/local/lib/python3.5/dist-packages/peewee-3.8.0-py3.5-linux-armv7l.egg/peewee.py", line 1705, in _ensure_execution
    self.execute()
  File "/usr/local/lib/python3.5/dist-packages/peewee-3.8.0-py3.5-linux-armv7l.egg/peewee.py", line 1622, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/peewee-3.8.0-py3.5-linux-armv7l.egg/peewee.py", line 1693, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.5/dist-packages/peewee-3.8.0-py3.5-linux-armv7l.egg/peewee.py", line 1844, in _execute
    cursor = database.execute(self)
  File "/usr/local/lib/python3.5/dist-packages/peewee-3.8.0-py3.5-linux-armv7l.egg/peewee.py", line 2724, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.5/dist-packages/peewee-3.8.0-py3.5-linux-armv7l.egg/peewee.py", line 2718, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.5/dist-packages/peewee-3.8.0-py3.5-linux-armv7l.egg/peewee.py", line 2509, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.5/dist-packages/peewee-3.8.0-py3.5-linux-armv7l.egg/peewee.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/peewee-3.8.0-py3.5-linux-armv7l.egg/peewee.py", line 2711, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such column: t1.email
10.9.200.6 - - [04/Jan/2019 09:26:53] "POST /login HTTP/1.1" 500 -

**Comment by rickyosser** [comment]
Check issue #14 , the error is because the initial lwp.db is to old.
